services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
  nginx:
      build:
        context: ./requirements/nginx
      image: nginx
      container_name: nginx
      restart: on-failure
      depends-on:
        - mariadb
      networks:
        - inception
      env_file:
        - .env
      ports:
        - "443:443"


networks:
  inception:

volumes:
  db_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/YOUR_LOGIN/data/mariadb